def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]
pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "OracleJDK8"
    }

    environment {
        cluster = "vproprod"
        service = "vproprodsvc"
    }

    stages {        
        stage ('Deploy to ECS prod environment') {
            steps {
                script {
                    withAWS(credentials: 'awscreds', region: 'us-east-1'){
                        sh 'aws ecs update-service --cluster $cluster --service $service --force-new-deployment'
                    }
                }
            }
        }
    }
    post {
            always {
                echo 'Slack Notifications.'
                slackSend channel: '#jenkinscicd', 
                color: COLOR_MAP[currentBuild.currentResult], 
                message: "Build Number: ${env.BUILD_NUMBER} \n Build Status: ${currentBuild.currentResult} \n Build URL: ${env.BUILD_URL} \n Build Logs: ${env.BUILD_URL}console"
            }
            
    }
}